from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtMultimedia import *
from PyQt6.QtMultimediaWidgets import QVideoWidget
from PyQt6.QtCore import QUrl
from PyQt6.QtCore import Qt


class MainUiWindow(object):
    def setup_ui(self, main_window) -> None:
        main_window.setObjectName("MainWindow")
        main_window.resize(400, 600)
        main_window.setMinimumSize(QtCore.QSize(400, 600))
        main_window.setMaximumSize(QtCore.QSize(400, 600))
        self.central_widget = QtWidgets.QWidget(parent=main_window)
        self.central_widget.setObjectName("central_widget")

        font = QtGui.QFont()
        font.setPointSize(35)
        self.pushButton_channelUp = QtWidgets.QPushButton(parent=self.central_widget)
        self.pushButton_channelUp.setGeometry(QtCore.QRect(130, 280, 31, 91))
        self.pushButton_channelUp.setFont(font)
        self.pushButton_channelUp.setObjectName("pushButton_channelUp")
        self.pushButton_channelDown = QtWidgets.QPushButton(parent=self.central_widget)
        self.pushButton_channelDown.setGeometry(QtCore.QRect(130, 370, 31, 91))

        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.pushButton_channelDown.setFont(font)
        self.pushButton_channelDown.setObjectName("pushButton_channelDown")
        self.pushButton_backButton = QtWidgets.QPushButton(parent=self.central_widget)
        self.pushButton_backButton.setGeometry(QtCore.QRect(180, 280, 41, 31))

        font = QtGui.QFont()
        font.setPointSize(23)
        self.pushButton_backButton.setFont(font)
        self.pushButton_backButton.setObjectName("pushButton_backButton")
        self.pushButton_digit5 = QtWidgets.QPushButton(parent=self.central_widget)
        self.pushButton_digit5.setGeometry(QtCore.QRect(180, 510, 41, 24))

        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_digit5.setFont(font)
        self.pushButton_digit5.setObjectName("pushButton_digit5")
        self.pushButton_volumeUp = QtWidgets.QPushButton(parent=self.central_widget)
        self.pushButton_volumeUp.setGeometry(QtCore.QRect(240, 280, 31, 91))

        font = QtGui.QFont()
        font.setPointSize(32)
        self.pushButton_volumeUp.setFont(font)
        self.pushButton_volumeUp.setObjectName("pushButton_volumeUp")
        self.pushButton_muteButton = QtWidgets.QPushButton(parent=self.central_widget)
        self.pushButton_muteButton.setGeometry(QtCore.QRect(180, 420, 41, 31))

        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.pushButton_muteButton.setFont(font)
        icon = QtGui.QIcon.fromTheme("mute.png")
        self.pushButton_muteButton.setIcon(icon)
        self.pushButton_muteButton.setProperty("m", QtGui.QColor(0, 232, 0))
        self.pushButton_muteButton.setObjectName("pushButton_muteButton")
        self.pushButton_digit3 = QtWidgets.QPushButton(parent=self.central_widget)
        self.pushButton_digit3.setGeometry(QtCore.QRect(230, 480, 41, 24))

        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_digit3.setFont(font)
        self.pushButton_digit3.setObjectName("pushButton_digit3")
        self.pushButton_volumeDown = QtWidgets.QPushButton(parent=self.central_widget)
        self.pushButton_volumeDown.setGeometry(QtCore.QRect(240, 370, 31, 91))

        font = QtGui.QFont()
        font.setPointSize(32)
        self.pushButton_volumeDown.setFont(font)
        self.pushButton_volumeDown.setObjectName("pushButton_volumeDown")
        self.pushButton_digit0 = QtWidgets.QPushButton(parent=self.central_widget)
        self.pushButton_digit0.setGeometry(QtCore.QRect(180, 570, 41, 24))

        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_digit0.setFont(font)
        self.pushButton_digit0.setObjectName("pushButton_digit0")
        self.pushButton_digit2 = QtWidgets.QPushButton(parent=self.central_widget)
        self.pushButton_digit2.setGeometry(QtCore.QRect(180, 480, 41, 24))

        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_digit2.setFont(font)
        self.pushButton_digit2.setObjectName("pushButton_digit2")
        self.pushButton_digit6 = QtWidgets.QPushButton(parent=self.central_widget)
        self.pushButton_digit6.setGeometry(QtCore.QRect(230, 510, 41, 24))

        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_digit6.setFont(font)
        self.pushButton_digit6.setObjectName("pushButton_digit6")
        self.pushButton_digit8 = QtWidgets.QPushButton(parent=self.central_widget)
        self.pushButton_digit8.setGeometry(QtCore.QRect(180, 540, 41, 24))

        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_digit8.setFont(font)
        self.pushButton_digit8.setObjectName("pushButton_digit8")
        self.pushButton_digit9 = QtWidgets.QPushButton(parent=self.central_widget)
        self.pushButton_digit9.setGeometry(QtCore.QRect(230, 540, 41, 24))

        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_digit9.setFont(font)
        self.pushButton_digit9.setObjectName("pushButton_digit9")
        self.pushButton_playPause = QtWidgets.QPushButton(parent=self.central_widget)
        self.pushButton_playPause.setGeometry(QtCore.QRect(180, 350, 41, 31))

        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_playPause.setFont(font)
        self.pushButton_playPause.setObjectName("pushButton_playPause")
        self.pushButton_digit1 = QtWidgets.QPushButton(parent=self.central_widget)
        self.pushButton_digit1.setGeometry(QtCore.QRect(130, 480, 41, 24))

        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_digit1.setFont(font)
        self.pushButton_digit1.setObjectName("pushButton_digit1")
        self.pushButton_digit7 = QtWidgets.QPushButton(parent=self.central_widget)
        self.pushButton_digit7.setGeometry(QtCore.QRect(130, 540, 41, 24))

        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_digit7.setFont(font)
        self.pushButton_digit7.setObjectName("pushButton_digit7")
        self.pushButton_digit4 = QtWidgets.QPushButton(parent=self.central_widget)
        self.pushButton_digit4.setGeometry(QtCore.QRect(130, 510, 41, 24))

        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.pushButton_digit4.setFont(font)
        self.pushButton_digit4.setObjectName("pushButton_digit4")
        self.pushButton_power = QtWidgets.QPushButton(parent=self.central_widget)
        self.pushButton_power.setGeometry(QtCore.QRect(240, 230, 31, 31))

        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_power.setFont(font)
        self.pushButton_power.setObjectName("pushButton_power")
        self.lcdNumber_channelNum = QtWidgets.QLCDNumber(parent=self.central_widget)
        self.lcdNumber_channelNum.setGeometry(QtCore.QRect(280, 235, 100, 35))

        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber_channelNum.setFont(font)
        self.lcdNumber_channelNum.setStyleSheet("QLCDNumber{\n"
                                                "    color: rgb(28, 168, 166);    \n"
                                                "    background-color: rgb(0, 0, 0);\n"
                                                "}")
        self.lcdNumber_channelNum.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.lcdNumber_channelNum.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.lcdNumber_channelNum.setLineWidth(1)
        self.lcdNumber_channelNum.setMidLineWidth(0)
        self.lcdNumber_channelNum.setSmallDecimalPoint(False)
        self.lcdNumber_channelNum.setDigitCount(5)
        self.lcdNumber_channelNum.setMode(QtWidgets.QLCDNumber.Mode.Dec)
        self.lcdNumber_channelNum.setSegmentStyle(QtWidgets.QLCDNumber.SegmentStyle.Filled)
        self.lcdNumber_channelNum.setProperty("value", 5.0)
        self.lcdNumber_channelNum.setProperty("intValue", 0)
        self.lcdNumber_channelNum.setProperty("color", QtGui.QColor(0, 232, 0))
        self.lcdNumber_channelNum.setObjectName("lcdNumber_channelNum")
        self.progressBar_volumeBar = QtWidgets.QProgressBar(parent=self.central_widget)
        self.progressBar_volumeBar.setGeometry(QtCore.QRect(310, 285, 40, 175))
        self.progressBar_volumeBar.setProperty("value", 0)
        self.progressBar_volumeBar.setObjectName("progressBar_volumeBar")
        self.progressBar_volumeBar.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.image_display = QtWidgets.QLabel(parent=self.central_widget)
        self.image_display.setEnabled(True)
        self.image_display.setGeometry(QtCore.QRect(20, 20, 361, 201))
        self.image_display.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.image_display.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.image_display.setLineWidth(1)
        self.image_display.setText("")
        self.image_display.setPixmap(QtGui.QPixmap())
        self.image_display.setScaledContents(True)
        self.image_display.setObjectName("image_display")
        self.image_display.raise_()
        self.pushButton_channelUp.raise_()
        self.pushButton_channelDown.raise_()
        self.pushButton_backButton.raise_()
        self.pushButton_digit5.raise_()
        self.pushButton_volumeUp.raise_()
        self.pushButton_muteButton.raise_()
        self.pushButton_digit3.raise_()
        self.pushButton_volumeDown.raise_()
        self.pushButton_digit0.raise_()
        self.pushButton_digit2.raise_()
        self.pushButton_digit6.raise_()
        self.pushButton_digit8.raise_()
        self.pushButton_digit9.raise_()
        self.pushButton_playPause.raise_()
        self.pushButton_digit1.raise_()
        self.pushButton_digit7.raise_()
        self.pushButton_digit4.raise_()
        self.pushButton_power.raise_()

        self.media_player = QMediaPlayer(parent=self.central_widget)
        self.media_player.setSource(QUrl.fromLocalFile("Channels/sample_960x540.mp4"))
        self.video_widget = QVideoWidget(parent=self.central_widget)
        self.video_widget.setGeometry(QtCore.QRect(20, 20, 361, 201))
        self.media_player.setVideoOutput(self.video_widget)

        self.progressBar_volumeBar.raise_()
        self.lcdNumber_channelNum.raise_()

        main_window.setCentralWidget(self.central_widget)

        self.re_translate_ui(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def re_translate_ui(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("MainWindow", "TV Remote"))
        self.pushButton_channelUp.setText(_translate("MainWindow", "⬆"))
        self.pushButton_channelDown.setText(_translate("MainWindow", "⬇"))
        self.pushButton_backButton.setText(_translate("MainWindow", "◀"))
        self.pushButton_digit5.setText(_translate("MainWindow", "5"))
        self.pushButton_volumeUp.setText(_translate("MainWindow", "+"))
        self.pushButton_muteButton.setText(_translate("MainWindow", "🔇"))
        self.pushButton_digit3.setText(_translate("MainWindow", "3"))
        self.pushButton_volumeDown.setText(_translate("MainWindow", "−"))
        self.pushButton_digit0.setText(_translate("MainWindow", "0"))
        self.pushButton_digit2.setText(_translate("MainWindow", "2"))
        self.pushButton_digit6.setText(_translate("MainWindow", "6"))
        self.pushButton_digit8.setText(_translate("MainWindow", "8"))
        self.pushButton_digit9.setText(_translate("MainWindow", "9"))
        self.pushButton_playPause.setText(_translate("MainWindow", "⏯"))
        self.pushButton_digit1.setText(_translate("MainWindow", "1"))
        self.pushButton_digit7.setText(_translate("MainWindow", "7"))
        self.pushButton_digit4.setText(_translate("MainWindow", "4"))
        self.pushButton_power.setText(_translate("MainWindow", "⏻"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = MainUiWindow()
    ui.setup_ui(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
